# Site settings
title: Albert Guedes | Software Developer
description: "Senior software developer specializing in PHP, Python, and Machine Learning."
url: "https://albertguedes.github.io"
author:
  name: "Albert R. C. Guedes"
  email: "albert@teko.net.br"
  url: "https://albertguedes.github.io"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "2.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
