# Site settings
title: Albert Guedes | Desenvolvedor de Software
description: "A mais de 12 anos desenvolvendo sites e aplicativos web."
url: "https://albertguedes.github.io"
author:
  name: "Albert R. Carnier Guedes"
  email: "albertguedes@hotmail.com"
  url: "https://albertguedes.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
